Added Generated Code | Service Version 2020-10-02
Azure/azure-storage-blob-go pull request #314
Opened 2021-12-21 07:09 UTC by mohsha-msft

2021-12-29 01:49 UTC, zezha-msft requested changes

2021-12-30 05:40 UTC, mohsha-msft commented on azblob/access_conditions.go
> -	IfMatch           ETag
Yes, the input of service has changed from *ETag to *String. We can keep it like before by defining ETag struct on our own.

2022-01-10 21:20 UTC, zezha-msft commented on azblob/access_conditions.go
> -	IfMatch           ETag
Can we avoid the breaking change with a README directive?

2022-01-11 08:35 UTC, mohsha-msft commented on azblob/access_conditions.go
> -	IfMatch           ETag
Sure. https://github.com/Azure/azure-storage-blob-go/pull/315 Here's another one.

2022-01-11 08:35 UTC, closed without merging

2022-01-11 08:35 UTC, mohsha-msft commented
https://github.com/Azure/azure-storage-blob-go/pull/315